<?php

use Illuminate\Database\Seeder;
use App\Parameter;

class ParametersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Parameter::insert([
            [
                'analysis' => '(Cd) Cadmium',
                'method' => 'none',
                'price' => '740.00',
                'station' => '1',
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Ca) Calcium',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Cr) Chromium',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Co) Cobalt',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Cu) Copper',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Fe) Iron',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Pb) Lead',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Ni) Nickel',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Ne) Sodium',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(K) Potassium',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Sb) Antimony',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Au) Gold',
                'method' => 'none',
                'price' => '1320.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Hg) Mercury',
                'method' => 'none',
                'price' => '1320.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Mg) Magnesium',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Mn) Manganese',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Se) Selenium',
                'method' => 'none',
                'price' => '1650.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Ag) Silver',
                'method' => 'none',
                'price' => '1100.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Sr) Strontium',
                'method' => 'none',
                'price' => '1100.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Sn) Tin',
                'method' => 'none',
                'price' => '1100.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(Zn) Zinc',
                'method' => 'none',
                'price' => '740.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '(As) Arsenic',
                'method' => 'none',
                'price' => '1650.00',
                'station' => 1,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Escherichia Coli',
                'method' => 'Membrane Filtration for drinking water samples',
                'price' => '540.00',
                'station' => 3,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Fecial Coliforms',
                'method' => 'Membrane Filtration for drinking water samples',
                'price' => '510.00',
                'station' => 3,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Coliforms',
                'method' => 'Membrane Filtration for drinking water samples',
                'price' => '810.00',
                'station' => 3,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Heterotrophic Plate Count',
                'method' => 'Pour Plate Method',
                'price' => '845.00',
                'station' => 3,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Fecal Coliforms, Total Coliforms',
                'method' => 'Multiple Tube Fermentation Technique for waste water and surface water samples',
                'price' => '1430.00',
                'station' => 3,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Acidity',
                'method' => 'none',
                'price' => '300.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Bicarbonate Alkalinity',
                'method' => 'none',
                'price' => '330.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Carbonate Alkalinity',
                'method' => 'none',
                'price' => '330.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Hydroxide Alkalinity',
                'method' => 'none',
                'price' => '330.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Phenolphtalein Alkalinity',
                'method' => 'none',
                'price' => '330.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Alkalinity / Methyl Orange Alkalinity',
                'method' => 'none',
                'price' => '330.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Free Carbon Dioxide',
                'method' => 'none',
                'price' => '330.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Carbon Dioxide',
                'method' => 'none',
                'price' => '330.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Chloride',
                'method' => 'none',
                'price' => '550.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Chlorine Disenfectant, residual',
                'method' => 'none',
                'price' => '420.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Chromium (VI)',
                'method' => 'none',
                'price' => '715.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Calcium Hardness',
                'method' => 'none',
                'price' => '330.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Magnesium Hardness',
                'method' => 'none',
                'price' => '445.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Hardness',
                'method' => 'none',
                'price' => '385.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Iron,total',
                'method' => 'none',
                'price' => '715.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Iodine',
                'method' => 'none',
                'price' => '500.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Ammonia-N',
                'method' => 'none',
                'price' => '715.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Nitrate-N',
                'method' => 'none',
                'price' => '715.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Nitrite-N',
                'method' => 'none',
                'price' => '660.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Organic-N',
                'method' => 'none',
                'price' => '1210.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Nitrogen',
                'method' => 'none',
                'price' => '1500.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Kjeldahl-N',
                'method' => 'none',
                'price' => '1500.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Urea-N',
                'method' => 'none',
                'price' => '1000.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Biochemical Oxygen Demand',
                'method' => 'none',
                'price' => '1320.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Chemical Oxygen Demand',
                'method' => 'none',
                'price' => '946.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Disolved Oxygen',
                'method' => 'none',
                'price' => '946.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Oil and Grease',
                'method' => 'none',
                'price' => '946.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Phosphate',
                'method' => 'none',
                'price' => '540.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Phosphorus,total',
                'method' => 'none',
                'price' => '605.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Salinity',
                'method' => 'none',
                'price' => '660.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Silica',
                'method' => 'none',
                'price' => '715.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Sulfate',
                'method' => 'none',
                'price' => '550.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Sulfide',
                'method' => 'none',
                'price' => '550.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Surfactants',
                'method' => 'none',
                'price' => '1500.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Color(Aparent)',
                'method' => 'none',
                'price' => '330.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Color(True)',
                'method' => 'none',
                'price' => '330.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Conductivity',
                'method' => 'none',
                'price' => '120.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'pH',
                'method' => 'none',
                'price' => '120.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Temperature',
                'method' => 'none',
                'price' => '120.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Turbidity',
                'method' => 'none',
                'price' => '360.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Dissolved Solids',
                'method' => 'none',
                'price' => '410.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Suspended Solids',
                'method' => 'none',
                'price' => '410.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Solids',
                'method' => 'none',
                'price' => '410.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Settleable Solids',
                'method' => 'none',
                'price' => '410.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Volatile Suspended Solids',
                'method' => 'none',
                'price' => '495.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Volatile Solids',
                'method' => 'none',
                'price' => '495.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '% Free Acid',
                'method' => 'none',
                'price' => '770.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '% Purity',
                'method' => 'none',
                'price' => '880.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Chloride',
                'method' => 'none',
                'price' => '660.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Nitrate',
                'method' => 'none',
                'price' => '770.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Nitrite',
                'method' => 'none',
                'price' => '715.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Sulfate',
                'method' => 'none',
                'price' => '1320.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Nitrogen',
                'method' => 'none',
                'price' => '1430.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Phosphorus',
                'method' => 'none',
                'price' => '1210.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Potassium (AAS)',
                'method' => 'none',
                'price' => '1240.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Moisture(Oven Method)',
                'method' => 'none',
                'price' => '660.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '% Acidity',
                'method' => 'none',
                'price' => '650.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '% purity ACIDS/BASES',
                'method' => 'none',
                'price' => '650.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '% purity Chlorine/Chloride',
                'method' => 'none',
                'price' => '715.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '% purity MAP',
                'method' => 'none',
                'price' => '1210.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '% purity other chemicals',
                'method' => 'none',
                'price' => '770.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Ash',
                'method' => 'Furnace',
                'price' => '685.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Fixed carbon',
                'method' => 'Calculation',
                'price' => '660.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Moisture',
                'method' => 'Oven',
                'price' => '660.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Volatile combustible matter',
                'method' => 'Furnace',
                'price' => '685.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Sulfur',
                'method' => 'Gravimetric',
                'price' => '685.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Alumina',
                'method' => 'Gravimetric',
                'price' => '1210.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Calcium oxide',
                'method' => 'Titrimetric',
                'price' => '1210.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Chloride',
                'method' => 'Argentometric',
                'price' => '1210.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Iron(III)oxide',
                'method' => 'Spectrophotometric',
                'price' => '1210.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Loss on Ignition',
                'method' => 'Oven',
                'price' => '990.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Magnesium oxide',
                'method' => 'Gravimetric',
                'price' => '1210.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Moisture',
                'method' => 'Oven',
                'price' => '660.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Organic Matter',
                'method' => 'Walkley Black',
                'price' => '1320.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'pH',
                'method' => 'Electode',
                'price' => '355.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Phosphorus',
                'method' => 'Spectrophotometric',
                'price' => '1210.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Silica',
                'method' => 'Gravimetric',
                'price' => '1210.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Nitrogen',
                'method' => 'Kjeldahl',
                'price' => '1430.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Sulfur',
                'method' => 'Gravimetric',
                'price' => '1320.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => '0.02 N EDTA Solution',
                'method' => 'none',
                'price' => '715.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Calcium Carbonate Solution',
                'method' => 'none',
                'price' => '715.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Standard Iodine Solution 0.10 N',
                'method' => 'none',
                'price' => '1100.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Sodium Carbonate Standard 0.05 N',
                'method' => 'none',
                'price' => '605.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Total Alk indicator',
                'method' => 'none',
                'price' => '1100.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Phenolphthalein indicator',
                'method' => 'none',
                'price' => '770.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'TH buffer solution',
                'method' => 'none',
                'price' => '605.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'TH indicator',
                'method' => 'none',
                'price' => '935.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'NaOH Buffer Solution',
                'method' => 'none',
                'price' => '605.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'Methyl Orange indicator',
                'method' => 'none',
                'price' => '605.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
            [
                'analysis' => 'CaH indicator',
                'method' => 'none',
                'price' => '605.00',
                'station' => 2,
                'managedBy' => 'Test Admin',
                'managedDate' => new DateTime,
            ],
        ]);
    }
}
